Repository Code-Duddies/TaskMaster, pull requests merged in 2024-05, with the labels that each got.

#1 Add file extensions and add task on enter key
  CSS
  Html
  JS
  index.html
  script.js
  styles.css
Labels: enhancement

#3 Add README, CODEOWNERS, and ESLint
  .gitignore
  .husky/pre-commit
  .lintstagedrc.json
  .prettierrc
  CODEOWNERS
  README.md
  eslint.config.mjs
  package-lock.json
  package.json
  src/css/styles.css
  src/index.html
  src/js/script.js
Labels: infrastructure

#22 Create pr_agent.yml
  .github/workflows/pr_agent.yml
Labels: configuration changes, Review effort [1-5]: 2
